sudo: required
services:
  - docker    

before_install:
  - docker build -t tomasoares/react-test -f ./client/Dockerfile.dev ./client
    
script:
  - docker run -e CI=true tomasoares/react-test npm test
  
after_success:
  - docker build -t tomasoares/fibonacci-client ./client
  - docker build -t tomasoares/fibonacci-nginx ./nginx
  - docker build -t tomasoares/fibonacci-server ./server
  - docker build -t tomasoares/fibonacci-worker ./worker
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push tomasoares/fibonacci-client
  - docker push tomasoares/fibonacci-nginx
  - docker push tomasoares/fibonacci-server
  - docker push tomasoares/fibonacci-worker
  
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "fibonacci-docker"
  env: "FibonacciDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-267699482760"
  bucket_path: "fibonacci-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY